name: test_e2e_invoice_base
on:
  pull_request:
    types: [opened, reopened]
    paths:
      - 'app/templates/invoice.html'
jobs:
  Cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          working-directory: tests_e2e
