name: test_models
on:
  pull_request:
    types: [opened, reopened]
    paths:
      - 'app/models.py'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-of-models:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask
          pip install flask_cors
          pip install SQLAlchemy 
          pip install Flask-SQLAlchemy 
          pip install flask-marshmallow 
          pip install marshmallow-sqlalchemy
          pip install Flask-Migrate 
          pip install Pillow 
          pip install flask-login
          pip install python-dateutil
      - name: Flask Data Migration
        run: |
          cd app
          echo "FLASK_APP ENV=$FLASK_APP"
          flask db init
          flask db migrate
          flask db upgrade
          python seeder.py
          cd ../tests
          python -m unittest -v
        env:
          FLASK_APP : models.py
